### ISSUE TITLE
So where would I find the code for this

### ISSUE THREAD

**Issue by DragonFyZex** [ellaism/volunteer#3]

**Comment by ellaismer** [comment]
Ellaism is mostly compatible with many Ethereum blockchains. Parity (https://github.com/paritytech/parity) is currently the main client used for Ellaism.

**Comment by ellaismer** [comment]
There's indeed a plan to create a fork of Parity and use native contracts to improve the EVM performance. But that's long way in the future.

If that doesn't answer your question, feel free to reopen this issue. :)
